server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:////home/fecarvalho/Documents/Estudos/FIAP/APIs/Trabalho/FIAP-Service-Architecture-API-Mobile-Architecture/ConfigServer/src/main/resources/config/amazon-service